MINERAL_TO_COMMODITY = {
    'Hematite':        {'metals': ['Iron', 'Steel'],          'uses': ['Construction', 'Vehicles', 'Infrastructure']},
    'Goethite':        {'metals': ['Iron'],                   'uses': ['Pigments', 'Steel production']},
    'Magnetite':       {'metals': ['Iron', 'Steel'],          'uses': ['Electronics', 'Construction']},
    'Jarosite':        {'metals': ['Iron', 'Gold (indirect)'],'uses': ['Gold processing indicator', 'Sulfuric acid']},
    'Chalcopyrite':    {'metals': ['Copper', 'Gold'],         'uses': ['Electrical wiring', 'Electronics', 'Coins']},
    'Sphalerite':      {'metals': ['Zinc', 'Silver'],         'uses': ['Galvanizing steel', 'Batteries', 'Sunscreen']},
    'Galena':          {'metals': ['Lead', 'Silver'],         'uses': ['Batteries', 'Radiation shielding', 'Historical pipes']},
    'Pyrite':          {'metals': ['Gold (indicator)', 'Sulfur'], 'uses': ['Sulfuric acid production', 'Gold exploration']},
    'Chromite':        {'metals': ['Chromium'],               'uses': ['Stainless steel', 'Chrome plating', 'Dyes']},
    'Alunite':         {'metals': ['Aluminum', 'Potassium'],  'uses': ['Alum production', 'Deodorants', 'Water treatment']},
    'Kaolinite':       {'metals': [],                         'uses': ['Porcelain', 'Paper coating', 'Toothpaste', 'Paint']},
    'Montmorillonite': {'metals': [],                         'uses': ['Cat litter', 'Drilling mud', 'Medicine', 'Cosmetics']},
    'Illite':          {'metals': [],                         'uses': ['Ceramics', 'Cement', 'Soil conditioner']},
    'Smectite':        {'metals': [],                         'uses': ['Drilling fluids', 'Wine clarification', 'Pharmaceuticals']},
    'Chlorite':        {'metals': [],                         'uses': ['Indicator of metamorphic gold deposits', 'Ceramics']},
    'Gypsum':          {'metals': [],                         'uses': ['Plaster', 'Drywall', 'Cement retarder', 'Fertilizer']},
    'Calcite':         {'metals': [],                         'uses': ['Cement', 'Lime', 'Antacids', 'Paper']},
    'Dolomite':        {'metals': ['Magnesium'],              'uses': ['Steel making', 'Glass', 'Cement', 'Agriculture']},
    'Magnesite':       {'metals': ['Magnesium'],              'uses': ['Refractory bricks', 'Fire resistance', 'Pharmaceuticals']},
    'Siderite':        {'metals': ['Iron'],                   'uses': ['Iron ore', 'Steel production']},
    'Serpentine':      {'metals': ['Nickel', 'Chromium'],     'uses': ['Asbestos (historical)', 'Nickel laterite ore']},
    'Olivine':         {'metals': ['Iron', 'Magnesium'],      'uses': ['Foundry sand', 'Refractory material', 'CO2 sequestration']},
    'Epidote':         {'metals': ['Gold (indicator)'],       'uses': ['Gemstone', 'Hydrothermal gold indicator']},
    'Actinolite':      {'metals': [],                         'uses': ['Historical asbestos', 'Nephrite jade']},
    'Talc':            {'metals': [],                         'uses': ['Talcum powder', 'Ceramics', 'Paint', 'Plastics']},
    'Pyrophyllite':    {'metals': ['Gold (indicator)'],       'uses': ['Ceramics', 'Refractory', 'Insecticide carrier']},
    'Alunite':         {'metals': ['Aluminum'],               'uses': ['Alum', 'Deodorant', 'Water purification']},
    'Augite':          {'metals': ['Iron', 'Magnesium'],      'uses': ['Geological indicator of mafic intrusions']},
    'Enstatite':       {'metals': ['Magnesium'],              'uses': ['Refractory ceramics', 'Gemstone']},
    'Quartz':          {'metals': ['Silicon'],                'uses': ['Glass', 'Electronics', 'Solar panels', 'Watches']},
    'Muscovite':       {'metals': [],                         'uses': ['Electronics insulation', 'Cosmetics', 'Paint shimmer']},
    'Water':           {'metals': [],                         'uses': ['Hydration', 'Agriculture', 'Logistics']},
}